name: py38
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4
  - appnope=0.1.2
  - asttokens=2.0.5
  - backcall=0.2.0
  - brotlipy=0.7.0
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - comm=0.1.2
  - cryptography=39.0.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - idna=3.4
  - ipykernel=6.19.2
  - ipython=8.7.0
  - jedi=0.18.1
  - jupyter_client=7.4.8
  - jupyter_core=5.1.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libopenblas=0.3.21
  - libsodium=1.0.18
  - llvm-openmp=15.0.7
  - matplotlib-inline=0.1.6
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - openssl=1.1.1s
  - parso=0.8.3
  - patsy=0.5.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - platformdirs=2.5.2
  - pooch=1.6.0
  - prompt-toolkit=3.0.36
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.8.15
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pyzmq=23.2.0
  - readline=8.2
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.40.0
  - stack_data=0.2.0
  - statsmodels=0.13.5
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.7.1
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.8
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
    - aiofiles==22.1.0
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - anyio==3.6.2
    - argcomplete==2.0.0
    - arviz==0.13.0
    - async-timeout==4.0.2
    - attrs==22.1.0
    - autocorrect==2.6.1
    - backports-zoneinfo==0.2.1
    - boto3==1.26.41
    - botocore==1.29.41
    - cftime==1.6.2
    - click==8.1.3
    - clikit==0.6.2
    - contourpy==1.0.5
    - crashtest==0.3.1
    - cycler==0.11.0
    - cython==0.29.32
    - dacite==1.7.0
    - deprecated==1.2.13
    - dill==0.3.6
    - dnspython==2.2.1
    - eventlet==0.33.2
    - fiftyone==0.18.0
    - fiftyone-brain==0.9.2
    - fiftyone-db==0.4.0
    - fonttools==4.38.0
    - frozenlist==1.3.1
    - future==0.18.2
    - glob2==0.7
    - graphql-core==3.2.3
    - greenlet==2.0.1
    - h11==0.14.0
    - h2==4.1.0
    - hpack==4.0.0
    - httpcore==0.16.3
    - httpstan==4.8.2
    - httpx==0.23.3
    - hypercorn==0.14.3
    - hyperframe==6.0.1
    - imageio==2.23.0
    - importlib-resources==5.12.0
    - jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.2.0
    - kaleido==0.2.1
    - kiwisolver==1.4.4
    - lvis==0.5.3
    - markupsafe==2.1.1
    - marshmallow==3.18.0
    - matplotlib==3.7.1
    - mongoengine==0.24.2
    - motor==3.1.1
    - multidict==6.0.2
    - ndjson==0.3.1
    - netcdf4==1.6.1
    - networkx==2.8.8
    - nltk==3.8.1
    - numpy==1.23.4
    - opencv-python==4.7.0.68
    - opencv-python-headless==4.7.0.68
    - packaging==21.3
    - pandas==1.5.1
    - pastel==0.2.1
    - patool==1.12
    - pillow==9.2.0
    - plotly==5.11.0
    - pprintpp==0.4.0
    - priority==2.0.0
    - psutil==5.9.4
    - pycocotools==2.0
    - pylev==1.4.0
    - pymongo==4.3.3
    - pyparsing==3.0.9
    - pypdf==3.2.1
    - pysimdjson==3.2.0
    - pystan==2.19.1.1
    - pytz==2022.5
    - pytz-deprecation-shim==0.1.0.post0
    - pywavelets==1.4.1
    - pyyaml==6.0
    - regex==2022.10.31
    - requests==2.28.1
    - retrying==1.3.4
    - rfc3986==1.5.0
    - s3transfer==0.6.0
    - scikit-image==0.19.3
    - scikit-learn==1.2.0
    - scipy==1.9.3
    - sniffio==1.3.0
    - sortedcontainers==2.4.0
    - sse-starlette==0.10.3
    - sseclient-py==1.7.2
    - starlette==0.20.4
    - strawberry-graphql==0.138.1
    - tabulate==0.9.0
    - tenacity==8.1.0
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - toml==0.10.2
    - tqdm==4.64.1
    - typing-extensions==4.4.0
    - tzdata==2022.7
    - tzlocal==4.2
    - universal-analytics-python3==1.1.1
    - urllib3==1.26.13
    - voxel51-eta==0.8.1
    - webargs==8.2.0
    - wrapt==1.14.1
    - wsproto==1.2.0
    - xarray==2022.10.0
    - xarray-einstats==0.3.0
    - xmltodict==0.13.0
    - yarl==1.8.1
    - zipp==3.15.0
